name: CI-CD-action
env:
  EB_PACKAGE_S3_BUCKET_NAME: "flask-app-cicd-packages"
  EB_APPLICATION_NAME: "FlaskCICD"
  EB_ENVIRONMENT_NAME: "Flaskcicd-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v3
        with:
          python-verion: '3.8.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 app --count --select=E9,F63,F7,F82,W391 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 app --count --exit-zero --max-complexity=18 --max-line-length=107 --statistics
        
      - name: Run tests
        run: pytest tests

      - name: Success message
        run: echo "Tests finished successfully"
